language: csharp
solution: Chargify.sln
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore Chargify.sln
script:
  - wget http://nuget.org/nuget.exe
  - cp nuget.exe ./.nuget/NuGet.exe
  - chmod a+x ./.nuget/NuGet.exe
  - xbuild /p:Configuration=Release /p:DefineConstants="NUNIT" Chargify.sln